name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Generate self-contained package
        run: |
          git archive --format=tar --prefix=wp-two-factor-auth/ HEAD | (cd /var/tmp/ && tar xf -)
          cp composer.lock /var/tmp/wp-two-factor-auth/
          (cd /var/tmp/wp-two-factor-auth && composer install --no-dev --no-interaction)
          (cd /var/tmp && zip -r -9 wp-two-factor-auth.zip wp-two-factor-auth)

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v0.1.14
        with:
          generate_release_notes: true
          files: |
            /var/tmp/wp-two-factor-auth.zip
